### ISSUE TITLE
Unable to donate

### ISSUE THREAD

**Issue by rikalively** [ConvergenceUS/fundthisministry#64]
<img width="949" alt="screen shot 2016-12-22 at 10 00 09 pm" src="https://cloud.githubusercontent.com/assets/23104131/21446296/5da5c33c-c892-11e6-9336-73e367f12c7f.png">

I am unable to donate to any of the projects. Chris Hamel is also having this issue. This is the error message I get after filling out all of my information.

**Comment by debdiproy** [comment]
@rikalively I will look into this personally and resolve by today.

**Comment by rikalively** [comment]
How are we doing resolving this issue?

**Comment by rikalively** [comment]
I am still unable to donate to any of the projects. How soon can we resolve this?

**Comment by rikalively** [comment]
Please give me an update on this issue.

**Comment by debdiproy** [comment]
@rikalively  We are changing the experience of the donation and payment from the last week and this should be completed by this Thursday

**Comment by rikalively** [comment]
I just tried to donate and see that it hasn't been resolved. When do you think the updates will be completed?

**Comment by debdiproy** [comment]
@rikalively We have changed the system of creating project and payment account once that is complete there will not be this issue any more. You may have a word with Cameron in this regards.

**Comment by debdiproy** [comment]
@rikalively The system of setting up of project has been changed and we have tested donating after creating a new project so this should be working now and as per my last telephonic conversation with @camerontrimble I think it will be good if we can repost the old project through the new system that should resolve the problems for liketime.

**Comment by rikalively** [comment]
<img width="930" alt="screen shot 2017-02-07 at 12 06 46 pm" src="https://cloud.githubusercontent.com/assets/23104131/22702221/f5a36710-ed2d-11e6-9d9c-d838cf1e90a3.png">

I am still getting this issue and am unable to donate.

**Comment by bikash02** [comment]
@debdiproy please check and assist
